### ISSUE TITLE
1.5.x

### ISSUE THREAD

**Issue by cesarlopes** [pagarme/pagarme-opencart#13]
Notice: Undefined index: payment_tax_id in /home/operabou/public_html/loja/catalog/controller/payment/pagar_me_checkout.php on line 53

**Comment by rodrigosantiag** [comment]
Por favor, baixe a versão mais atual do módulo aqui: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22390

Não estão mais aceitando aqui meus pull request

**Comment by cesarlopes** [comment]
Olá,

Fiz a instalação da versão mais atual do módulo, mudou a mensagem de erro, já tentei limpar a pasta cache do vqmode o erro persistiu...

Notice: Undefined index: pagar_me_checkout_url in /home/user/public_html/loja/vqmod/vqcache/vq2-catalog_model_checkout_order.php on line 89

**Comment by cesarlopes** [comment]
Desculpe, já corrigi!

**Comment by cesarlopes** [comment]
Atualizei o módulo, a mensagem de erro sumiu, porem quando clico em confirmar a compra aparece a mensagem "Aguarde..." e não muda, já esperei mais de 15 minutos.... Na Dashboard da Pagar.me também não aparece nada, tem como debugar?

**Comment by rodrigosantiag** [comment]
Olá César.
O log de erros fica em sistema > mostrar log de erros.
Entretanto, sugiro que você desinstale o módulo, reinstale e veja se o erro
some. Tive que fazer algumas correçõs no BD, por isso a desinstalação se faz
necessária.
Qualquer coisa pode me enviar e-mail que ajudo pessoalmente.
E-mail: contato@santive.com
Abs!
Rodrigo Ramos Santiago


Em 28 de janeiro de 2016 15:13, César Lopes < notifications@github.com > escreveu:
Atualizei o módulo, a mensagem de erro sumiu, porem quando clico em confirmar a
compra aparece a mensagem "Aguarde..." e não muda, já esperei mais de 15
minutos.... Na Dashboard da Pagar.me também não aparece nada, tem como debugar?

**Comment by cesarlopes** [comment]
Rodrigo,

No log mostra a mensagem:
2016-01-29 11:30:06 - PHP Notice:  Undefined index: payment_tax_id in
/home/operabou/public_html/loja/catalog/controller/payment/pagar_me_cartao.php
on line 210

Você pode me ajudar?


-
César Lopes.

Em 28 de janeiro de 2016 16:27, Rodrigo Santiago <notifications@github.com>
escreveu:

**Comment by rodrigosantiag** [comment]
César, bom dia.
Isso ocorre porque o módulo exige que o campo CPF esteja ativo e seja
obrigatório.
Você pode fazer isso em Sistema > Usuários > Grupo de Usuários.
Se você utiliza algum módulo que crie o campo CPF, você deve alterar o módulo
para que o mesmo funcione.
Está aqui em minha lista uma tarefa para que eu acrescente este campo ao
formulário de cartão de crédito. Assim que executar atualizarei o módulo no site
do OpenCart, já que aqui meus pull requests não estão mais sendo aceitos.
Sugiro também que baixe o módulo do checkout pagar.me que desenvolvemos por
aqui, segue o link: 
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24780&filter_download_id=33&page=2
Rodrigo Ramos Santiago


Em 29 de janeiro de 2016 09:31, César Lopes < notifications@github.com > escreveu:
Rodrigo,

No log mostra a mensagem:
2016-01-29 11:30:06 - PHP Notice: Undefined index: payment_tax_id in
/home/operabou/public_html/ loja/catalog/controller/ payment/pagar_me_cartao.php
on line 210

Você pode me ajudar?


-
César Lopes.

Em 28 de janeiro de 2016 16:27, Rodrigo Santiago < notifications@github.com >
escreveu:

**Comment by cesarlopes** [comment]
Rodrigo, bom dia!

Eu estou utilizando a versão 1.5.4, os campos "CNPJ ou CPF" já estão como
obrigatório e mesmo assim o erro persiste.

https://www.operaboutique.com.br/loja/index.php?route=account/register


-
César Lopes.

Em 1 de fevereiro de 2016 10:07, Rodrigo Santiago <notifications@github.com>
escreveu:

**Comment by rodrigosantiag** [comment]
OI César.
Então, como eu disse vou ter que acrescentar o campo CPF ao formulário do cartão
de crédito.
Está na fila aqui para semana que vem.
O checkout pagar.me que te passei no e-mail anterior resolve.
Att.
Rodrigo Ramos Santiago


Em 1 de fevereiro de 2016 10:15, César Lopes < notifications@github.com > escreveu:
Rodrigo, bom dia!

Eu estou utilizando a versão 1.5.4, os campos "CNPJ ou CPF" já estão como
obrigatório e mesmo assim o erro persiste.

https://www.operaboutique.com. br/loja/index.php?route= account/register


-
César Lopes.

Em 1 de fevereiro de 2016 10:07, Rodrigo Santiago < notifications@github.com >
escreveu:

> César, bom dia.
> Isso ocorre porque o módulo exige que o campo CPF esteja ativo e seja
> obrigatório.
> Você pode fazer isso em Sistema > Usuários > Grupo de Usuários.
> Se você utiliza algum módulo que crie o campo CPF, você deve alterar o
> módulo
> para que o mesmo funcione.
> Está aqui em minha lista uma tarefa para que eu acrescente este campo ao
> formulário de cartão de crédito. Assim que executar atualizarei o módulo
> no site
> do OpenCart, já que aqui meus pull requests não estão mais sendo aceitos.
> Sugiro também que baixe o módulo do checkout pagar.me que desenvolvemos
> por
> aqui, segue o link:
>
> http://www.opencart.com/index. php?route=extension/extension/
info&extension_id=24780& filter_download_id=33&page=2

**Comment by cesarlopes** [comment]
Rodrigo, boa tarde!

O checkout funcionou certinho agora, porém quando a transação é concluída
deu o seguinte erro:

https://www.operaboutique.com.br/loja/index.php?route=payment/pagar_me_checkout/confirm

*Fatal error*: Uncaught exception 'Exception' with message 'Failed to
decode json from response. Response: Array' in
/home/operabou/public_html/loja/system/library/PagarMe/lib/Pagarme/Request.php:29
Stack trace: #0
/home/operabou/public_html/loja/system/library/PagarMe/lib/Pagarme/Model.php(48):
PagarMe_Request->run() #1
/home/operabou/public_html/loja/catalog/controller/payment/pagar_me_checkout.php(103):
PagarMe_Model::findById('test_transactio...') #2 [internal function]:
ControllerPaymentPagarMeCheckout->confirm() #3
/home/operabou/public_html/loja/vqmod/vqcache/vq2-system_engine_front.php(42):
call_user_func_array(Array, Array) #4
/home/operabou/public_html/loja/vqmod/vqcache/vq2-system_engine_front.php(29):
Front->execute(Object(Action)) #5
/home/operabou/public_html/loja/index.php(239):
Front->dispatch(Object(Action), Object(Action)) #6 {main} thrown in
*/home/operabou/public_html/loja/system/library/PagarMe/lib/Pagarme/Request.php*
on
line *29*


-
César Lopes.

Em 2 de fevereiro de 2016 14:26, Rodrigo Santiago <notifications@github.com>
escreveu:

**Comment by rodrigosantiag** [comment]
César, boa tarde.
Você baixou do link que te passei certo?
Se sim, peço que desinstale o módulo e depois instale de novo.
Fiz o teste no meu endereço de testes e rolou normal.
Att.
Rodrigo Ramos Santiago


Em 2 de fevereiro de 2016 15:06, César Lopes < notifications@github.com > escreveu:
Rodrigo, boa tarde!

O checkout funcionou certinho agora, porém quando a transação é concluída
deu o seguinte erro:

https://www.operaboutique.com. br/loja/index.php?route=
payment/pagar_me_checkout/ confirm

*Fatal error*: Uncaught exception 'Exception' with message 'Failed to
decode json from response. Response: Array' in
/home/operabou/public_html/ loja/system/library/PagarMe/ lib/Pagarme/Request.php:29
Stack trace: #0
/home/operabou/public_html/ loja/system/library/PagarMe/ lib/Pagarme/Model.php(48):
PagarMe_Request->run() #1
/home/operabou/public_html/ loja/catalog/controller/ payment/pagar_me_checkout.php( 103):
PagarMe_Model::findById('test_ transactio...') #2 [internal function]:
ControllerPaymentPagarMeChecko ut->confirm() #3
/home/operabou/public_html/ loja/vqmod/vqcache/vq2-system_ engine_front.php(42):
call_user_func_array(Array, Array) #4
/home/operabou/public_html/ loja/vqmod/vqcache/vq2-system_ engine_front.php(29):
Front->execute(Object(Action)) #5
/home/operabou/public_html/ loja/index.php(239):
Front->dispatch(Object(Action) , Object(Action)) #6 {main} thrown in
*/home/operabou/public_html/ loja/system/library/PagarMe/ lib/Pagarme/Request.php*
on
line *29*


-
César Lopes.

Em 2 de fevereiro de 2016 14:26, Rodrigo Santiago < notifications@github.com >
escreveu:

**Comment by cesarlopes** [comment]
Rodrigo, boa tarde!

Eu desinstalei e instalei novamente, o mesmo erro, estou utilizando a chave
de testes, pode ser isso?

Qual o procedimento correto para desinstalar e instalar novamente o módulo?

-
César Lopes.

Em 3 de fevereiro de 2016 12:52, Rodrigo Santiago <notifications@github.com>
escreveu:

**Comment by rodrigosantiag** [comment]
O procedimento seria is em extensões > Formas de Pagamento, desinstalar, fazer o
upload dos arquivos que você baixou no site do OpenCart (só para garantir) e
depois instalar novamente.
Se o erro persistir me passe no e-mail contato@santive.com o acesso FTP aos
arquivos.
Att.
Rodrigo Ramos Santiago


Em 3 de fevereiro de 2016 14:23, César Lopes < notifications@github.com > escreveu:
Rodrigo, boa tarde!

Eu desinstalei e instalei novamente, o mesmo erro, estou utilizando a chave
de testes, pode ser isso?

Qual o procedimento correto para desinstalar e instalar novamente o módulo?

-
César Lopes.

Em 3 de fevereiro de 2016 12:52, Rodrigo Santiago < notifications@github.com >
escreveu:

**Comment by murilohns** [comment]
Fala @cesarlopes, estou fechando essa issue, mas sinta-se a vontade para para reabri-la caso seja necessário :)
