### ISSUE TITLE
OpenCart 2.X instala mais não aparece opção no checkout

### ISSUE THREAD

**Issue by philsouza2016** [pagarme/pagarme-opencart#25]
Primeiro recebi um erro do log assim:
2016-11-22 18:01:25 - PHP Notice:  Undefined variable: help_text_botao in /home/brirc695/public_html/admin/view/template/payment/pagar_me_checkout.tpl on line 84

Verificando percebi que a variável que estava sendo chamada no formulário do dashboard estava com o nome errado, era help_texto_botão e estava help_text_botão. Corrigi e o logo parou de disparar erros. Porém, limpei o cache, ativei e desativei a extensão em pagamentos e não vejo nada aparecer no checkout. Vale comentar que estamos usando o tema Pavilion, mas temos dezenas de outras opções de pagamento e todas elas funcionam...

**Comment by philsouza2016** [comment]
Após resolver alguns problemas na instalação do módulo de cartão de credito apareceu nas opções de checkout, mas apresentou o seguinte erro:

2016-11-22 20:42:44 - Erro Pagar.me: #0 /home/brirc695/public_html/system/library/PagarMe/lib/Pagarme/Request.php(35): PagarMe_Exception::buildWithFullMessage(Array)
#1 /home/brirc695/public_html/system/library/PagarMe/lib/Pagarme/TransactionCommon.php(51): PagarMe_Request->run()
#2 /home/brirc695/public_html/catalog/controller/payment/pagar_me_cartao.php(44): PagarMe_TransactionCommon::calculateInstallmentsAmount('11410', '1', 1, '5')
#3 [internal function]: ControllerPaymentPagarMeCartao->index(Array)
#4 /home/brirc695/public_html/vqmod/vqcache/vq2-system_modification_system_engine_action.php(67): call_user_func(Array, Array)
#5 /home/brirc695/public_html/vqmod/vqcache/vq2-system_modification_system_engine_loader.php(12): Action->execute(Object(Registry))
#6 /home/brirc695/public_html/catalog/controller/checkout/confirm.php(409): Loader->controller('payment/pagar_m...')
#7 [internal function]: ControllerCheckoutConfirm->index(Array)
#8 /home/brirc695/public_html/vqmod/vqcache/vq2-system_modification_system_engine_action.php(67): call_user_func(Array, Array)
#9 /home/brirc695/public_html/system/modification/system/engine/front.php(42): Action->execute(Object(Registry))
#10 /home/brirc695/public_html/system/modification/system/engine/front.php(37): Front->execute(Object(Action))
#11 /home/brirc695/public_html/index.php(263): Front->dispatch(Object(Action), Object(Action))
#12 {main}

**Comment by devdrops** [comment]
Oi @philsouza2016!

Pode por favor passar o conteúdo da variável `$response` (em 2.x/upload/system/library/PagarMe/lib/Pagarme/Request.php#L26) aqui na issue? Ela pode conter alguns detalhes a mais sobre o que de fato veio na resposta, uma vez que o motivo da exceção disparada foi pelo `status` != 200.

**Comment by philsouza2016** [comment]
Olá, descobri que em modo teste o checkout aparece, em modo produção não, mas mesmo em modo teste na hora de finalizar a comprar ele apresenta o erro:

VM1152:35 Uncaught ReferenceError: PagarMe is not defined(…)

Exatamente no momento que ele vai fazer conexão com a Api com a chave de teste, ele não reconhece variável do pagarme.

**Comment by devdrops** [comment]
Olá @philsouza2016. Por favor, pode mostrar o output completo desse último erro?

No aguardo das suas respostas.

**Comment by philsouza2016** [comment]
Olá @devdrops  o erro é visto pelo console do google chrome, o erro completo é esse aqui:

**Uncaught ReferenceError: PagarMe is not defined
    at HTMLInputElement.eval (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:1:1), <anonymous>:35:9)
    at HTMLInputElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:8436)
    at HTMLInputElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:5139)**

O erro acontece na linha 35: 

**/*Função Pagar.me*/
PagarMe.encryption_key = "ek_test_xxxxxxxxxxxxxxxx";**

A chave de teste está correta.

**Comment by philsouza2016** [comment]
Vamos a próxima fase. Descobri que na instalação um parâmetro que insere no header o script que contém o PagarMe não funcionou, inclui na mão no header a linha:
<script src="https://assets.pagar.me/js/pagarme.min.js"></script>

Quando cliquei em finalizar a compra finalmente foi, pórem um novo erro foi disparado:

**Notice: Undefined index: message in /home/brirc695/public_html/system/modification/catalog/model/checkout/order.php on line 606Notice: Undefined offset: 1 in /home/brirc695/public_html/system/modification/catalog/model/checkout/order.php on line 610Warning: Cannot modify header information - headers already sent by (output started at /home/brirc695/public_html/index.php:102) in /home/brirc695/public_html/system/modification/system/library/response.php on line 17**

**Comment by philsouza2016** [comment]
Ok, agora o erro é interno, esse erro é gerado por uma modificação em um módulo de edição de emails para clientes chamado TMD. O problema real até agora mesmo foi o script que não foi inserido na home, de resto está tudo certo, as compras estão indo.

**Comment by ricardotulio** [comment]
Olá @philsouza2016,

Estou fechando esta issue pois o problema já foi solucionado.
