### ISSUE TITLE
Erro no QuickChekout do Theme Journal 2.8x

### ISSUE THREAD

**Issue by smfsoft** [pagarme/pagarme-opencart#27]
Eu uso o theme journal 2.8x com o QuickCheckout ativado, e exibia uma mensagem de erro ao selecionar este meio de pagamento. O problema estava no arquivo catalog\controller\payment\pagar_me_checkout.php, que duplicada o caminho do theme.
Linha 23: return $this->load->view('default/template/payment/pagar_me_checkout.tpl', $data);
Removam: default/template deixando assim:
return $this->load->view('payment/pagar_me_checkout.tpl', $data);

**Comment by murilohns** [comment]
resolvido com o Pull Request #41
