### ISSUE TITLE
The .zip file build is conflicting on every change

### ISSUE THREAD

**Issue by piiih** [pagarme/pagarme-opencart#36]
The .zip file always will go into conflict, because doesn't exist a .gitattributes setting this .zip file to binary. So, git try to merge this .zip file and this cause a conflict.

**Comment by murilohns** [comment]
We need to change the .zip releases method, at every change we have to refresh the .zip file. In this scenary if has much opened pull requests, all of then will be conflicting

**Comment by murilohns** [comment]
Fala @piiih , beleza? a solução é abrir um PR sem enviar o arquivo .ZIP nele. Quando o PR for aprovado, atualiza a branch com o ZIP e da o merge nele, ok? =)
