### ISSUE TITLE
No OpenCart 1.5 não mostra o boleto gerado

### ISSUE THREAD

**Issue by marcelorsoares** [pagarme/pagarme-opencart#40]
Bom dia,
instalei o plugin em uma loja com o OpenCart 1.5 mas quando seleciono a opção de gerar o boleto não mostra o boleto gerado, só redireciona para a página de pagamento concluído.

**Comment by vgsmith** [comment]
Boa tarde @marcelorsoares , como vai?

**Comment by vgsmith** [comment]
Boa tarde @marcelorsoares , como vai?

Recentemente lançamos uma nova versão da API do Pagar.me, o que afetou o fluxo para geração do boleto em algumas plataformas.

Estamos trabalhando na atualização dos módulos, assim que estiver disponível para versão 1.5 do Opencart te notificamos por aqui.

Qualquer outra dúvida é só chamar,
Abs

**Comment by marcelorsoares** [comment]
Boa tarde, @vgsmith!. 
Tudo bem, e com você?
Agradeço a atenção e fico no aguardo,

Abs

**Comment by murilohns** [comment]
Olá @marcelorsoares, seu problema já foi solucionado?

**Comment by marcelorsoares** [comment]
Bom dia, @murilohns, foi resolvido sim, obrigado por perguntar.

O que estava acontecendo é que o botão de gerar o boleto é exibido na mesma página de pagamento concluído. 

Além de passar despercebido, o tema que estou utilizando dificultava ainda mais a visualização do botão por conta do esquema de cores.

Vou reproduzir as instruções passadas a mim pelo Leonardo Barbosa, pois pode ser útil a outros usuários:

> Aparentemente o problema ocorre devido as classes dos botões do tema configurado em seu site, para corrigi-lo peço que substitua o arquivo **_/root_do_opencart/vqmod/xml/pagar_me_checkout.xml_** pelo que enviarei em anexo.

> Para contexto do que alterei, ele tentava buscar um botão com a classe igual à button​ e caso achasse incluiria o botão de impressão:

`<search position="before"><![CDATA[<div class="right"><a href="<?php echo $continue; ?>" class="button"><?php echo $button_continue; ?></a></div>]]></search>`

> A única coisa que alterei foi incluir a classe do botão que consta em seu tema:

`<search position="before">
                <![CDATA[<div class="right"><a href="<?php echo $continue; ?>" class="button btn btn-outline-black"><?php echo $button_continue; ?></a></div>]]>
</search>`
