### ISSUE TITLE
Versão 2.0 > não funciona

### ISSUE THREAD

**Issue by prhost** [pagarme/pagarme-opencart#5]
Na versão 2.0 do opencart, to tentando arrumar, mais tem muita coisa que mudou, o módulo vai ser atualizado?

**Comment by rodrigosantiag** [comment]
Olá Kallef.

O módulo vai ser atualizado sim.

A previsão é para a segunda quinzena de maio.

Abraço!

Rodrigo Ramos Santiago

Em 23 de abril de 2015 11:38, Kallef <notifications@github.com> escreveu:

**Comment by thebergamo** [comment]
@rodrigosantiag alguma novidade a respeito disso?

**Comment by ezanattatray** [comment]
?

**Comment by rodrigosantiag** [comment]
Caros, estou em contato com a Alessandra Girne para fecharmos o desenvolvimento
de um suite completo para OpenCart e Pagar.Me.
Att.
Rodrigo Ramos Santiago


2015-09-17 15:24 GMT-03:00 Evandro Zanatta < notifications@github.com > :
?
