### ISSUE TITLE
Problema para gerar boleto

### ISSUE THREAD

**Issue by alanaguiar26** [pagarme/pagarme-opencart#72]
Boa noite,

Sempre usei o modulo pagar.me em meu opencart e hoje percebi que o boleto não esta sendo gerado.
Tenho campo cpf personalizado em minha loja.

2017-11-07 21:49:19 - Erro Pagar.Me boleto: número do documento está faltando

2017-11-07 21:50:50 - Erro Pagar.Me boleto: número do documento está faltando

Sabe me dizer se mudou algo, ou como eu posso resolver?

caso queira testar a loja é https://lojaimports.com.br

**Comment by murilohns** [comment]
Olá @alanaguiar26 , realizei um teste em sua loja e o boleto foi gerado normalmente.

O problema permanece?

**Comment by alanaguiar26** [comment]
Bom dia,


Eu instalei o modulo mais recente e voltou a funcionar.

O modulo que eu tinha, não esta mais gerando o boleto.


Obrigado pelo retorno.




Enviado do Outlook<http://aka.ms/weboutlook>


________________________________
De: Murilo Henrique Nascimento Souza <notifications@github.com>
Enviado: quarta-feira, 8 de novembro de 2017 09:38
Para: pagarme/pagarme-opencart
Cc: alanaguiar26; Mention
Assunto: Re: [pagarme/pagarme-opencart] Problema para gerar boleto (#72)


Olá @alanaguiar26<https://github.com/alanaguiar26> , realizei um teste em sua loja e o boleto foi gerado normalmente.

O problema permanece?

**Comment by murilohns** [comment]
Ok @alanaguiar26 , obrigado pelo retorno!

Irei fechar essa Issue, mas caso tenha alguma dúvida fique a vontade para reabri-la
