### ISSUE TITLE
Falha na confirmação de pagamento ("value" is required)

### ISSUE THREAD

**Issue by FBXWEB** [pagarme/pagarme-opencart#85]
Saudações... 

Instalei a nova versão da Pasta API para OC 2.3.0.2, e agora estou recebendo uma mensagem de erro ao finalizar o pagamento com cartão de crédito: "value" is required

No console aparece a seguinte resposta JSON:

GET https://api.pagar.me/1/transactions/card_hash_key?...ryption_key=ek_test_f2PUs2eJpJTWJCGOoQYo3tn2JlrrLi | 200 |   | 193ms |  

POST index.php?route=extension/payment/pagar_me_cartao/payment    200 OK    1140ms	
RESPONSE: {"error":"\"value\" is required\n"}

Já tentei desinstalar e reinstalar algumas vezes, limpei várias vezes o CACHE, manualmente e pelo ADMIN, Limpei a pasta do cache do VQMod e nada resolve...

Alguém já passou ou está passando por essa situação?
Lembrando que estou utilizando com Chave de API e Chave de Criptografia de TESTE...
Era pra funcionar mesmo assim, não?

Será que alguém pode me ajudar?
Obrigado!

**Comment by FBXWEB** [comment]
E no cado do boleto aparece o seguinte erro:
child "type" fails because ["type" is required]

**Comment by jonatasmaxi** [comment]
Olá @FBXWEB. 
Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 
Este erro acontece devido a uma incompatibilidade com a versão de sua chave de API. 
Atualmente nossas integrações pro OpenCart só são compatíveis com as versões 2017-07-17 e a versão 2013-03-01 da API. 
Para resolver este problema precisaremos alterar a versão de sua chave de API. Para isso, peço gentilmente que envie um e-mail para suporte@pagar.me de um e-mail que possua privilégios de administrador da conta. Assim conseguimos fazer esta alteração para você, ok? 

Abracos, Jonatas.
