### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by medeirosrafael** [pagarme/pagarme-opencart#95]
Estou com erro nessa linha:
https://github.com/pagarme/pagarme-opencart/blob/master/API/2.x/upload/catalog/controller/payment/pagar_me.php#L61

e essa linha: https://github.com/pagarme/pagarme-opencart/blob/master/API/2.x/upload/catalog/controller/payment/pagar_me.php#L63

Ambos os campos existem.. eu coloquei um @ para evitar os warning.. mas é um erro do plugin ou sera que fiz algo errado na instalação/configuração?

**Comment by medeirosrafael** [comment]
Era um warning de undefined offset '5'.. Em ambas as linhas.
Eu tava logado

**Comment by murilohns** [comment]
@medeirosrafael, os campos customizáveis de seu site estavam habilitados quando você testou?

Nota: Os campos podem estar criados, mas podem estar desabilitados

**Comment by medeirosrafael** [comment]
@murilohns Sim.. inclusive com os nomes iguais ao do codigo "Número" e "complemento"

**Comment by murilohns** [comment]
@medeirosrafael, pode dizer qual a versão exata de seu opencart? Irei tentar simular esse problema

**Comment by murilohns** [comment]
fala @medeirosrafael, como você não retomou contato, estou fechando essa issue, mas sinta-se à vontade pra reabri-la se precisar.
